cc_library(
    name = "assimp",
    srcs = ["lib/libassimp.so"],
    hdrs = glob([
        "include/**/*.h",
        "include/**/*.hpp",
        "include/**/*.inl",
        ]),
    includes = ["include"],
    visibility = [
        "//visibility:public"
    ],
)