cc_library(
    name = "shader",
    srcs = ["Shader.cpp"],
    hdrs = ["Shader.h"],
    includes = [".."],
    deps = [
        "//include:log",
        "//include:gl_headers",
        "//dependency/glm:glm",
        "//dependency/glad:glad",
    ],
    visibility = ["//visibility:public"],
)
