cc_library(
    name = "egl_glad",
    srcs = ["glad/glad_egl.c"],
    hdrs = [
        "glad/eglplatform.h",
        "glad/glad_egl.h",
        "glad/khrplatform.h",
        "glad/glad.h"
    ],
    includes = ["."],
    visibility = [
        "//visibility:public"
    ],
)