cc_library(
    name = "postprocess",
    srcs = ["FboHandler.cpp"],
    hdrs = ["FboHandler.h"],
    includes = [".."],
    deps = [
        "//src/core/shader:shader",
        "//include:gl_headers",
        "//dependency/stb:stb",
        "//dependency/glm:glm",
        "//src:rhi",
    ],
    visibility = ["//visibility:public"],
)
