cc_library(
    name = "ktx",
    srcs = [
        "lib/libktx.so.4.4.2",
        "lib/libktx.so.4",
        "lib/libktx.so",
    ],
    hdrs = [
        "include/ktx.h",
        "include/ktxvulkan.h",
        "include/KHR/khr_df.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public"
    ],
)
