cc_library(
    name = "scene",
    srcs = ["Skybox.cpp"],
    hdrs = ["Skybox.h"],
    includes = [".."],
    deps = [
        "//src/core/common:common",
        "//src/core/shader:shader",
        "//include:gl_headers",
        "//dependency/glm:glm",
        "//dependency/stb:stb",
        "//dependency/glad:glad",
    ],
    visibility = ["//visibility:public"],
)
