cc_library(
    name = "texture",
    srcs = ["TextureCache.cpp"],
    hdrs = ["TextureCache.h"],
    includes = [".."],
    deps = [
        "//src/core/common:common",
        "//include:gl_headers",
        "//dependency/glm:glm",
        "//dependency/stb:stb",
        "//dependency/glad:glad",
    ],
    visibility = ["//visibility:public"],
)
