cc_library(
    name = "log",
    hdrs = [
        "log/mylog.h",
    ],
    includes = [
        ".",
    ],
    visibility = [
        "//visibility:public"
    ]
)

cc_library(
    name = "gl_headers",
    hdrs = [
        "gl/gl_headers.h",
    ],
    includes = [
        ".",
    ],
    deps = [
        "//dependency/glm:glm",
    ],
    visibility = [
        "//visibility:public"
    ]
)