cc_library(
    name = "camera",
    srcs = ["VirCamera.cpp"],
    hdrs = ["VirCamera.h"],
    includes = [".."],
    deps = [
        "//include:gl_headers",
        "//dependency/glm:glm",
        "//dependency/glad:glad",
    ],
    visibility = ["//visibility:public"],
)
